// flow-typed signature: ffbfd75d3b4c536f12c7c187edca4e56
// flow-typed version: <<STUB>>/neataptic_v^1.4.5/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'neataptic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'neataptic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'neataptic/dist/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/dist/worker' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.10/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.10/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.11/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.11/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.12/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.12/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.13/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.13/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.14/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.14/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.15/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.15/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.16/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.16/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.17/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.17/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.18/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.18/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.19/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.19/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.20/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.20/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.21/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.21/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.22/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.22/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.23/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.23/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.24/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.24/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.25/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.25/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.26/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.26/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.27/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.27/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.28/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.28/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.29/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.29/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.30/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.30/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.31/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.31/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.32/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.32/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.33/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.33/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.34/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.2.34/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.0/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.0/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.1/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.1/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.2/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.3/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.4/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.5/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.6/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.7/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.8/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.3.9/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.4.0/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.4.1/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.4.2/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.4.3/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.4.4/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/cdn/1.4.5/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/agar.ioai/field' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/agar.ioai/food' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/agar.ioai/import' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/agar.ioai/main' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/agar.ioai/player' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/agar.ioai/population' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/classifycolors/events' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/classifycolors/import' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/classifycolors/neural' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/classifycolors/randomColor' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/neuroevolution/events' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/neuroevolution/graph' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/neuroevolution/import' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/neuroevolution/neural' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/neuroevolution/webcola' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/playground/events' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/playground/graph' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/playground/import' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/playground/neural' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/target-seekingai/field' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/target-seekingai/graph' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/target-seekingai/import' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/target-seekingai/main' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/target-seekingai/player' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/target-seekingai/population' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/articles/target-seekingai/walker' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/base' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/bootstrap-3.0.3.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/highlight.pack' {
  declare module.exports: any;
}

declare module 'neataptic/docs/js/jquery-1.10.2.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/mkdocs/js/lunr.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/mkdocs/js/mustache.min' {
  declare module.exports: any;
}

declare module 'neataptic/docs/mkdocs/js/require' {
  declare module.exports: any;
}

declare module 'neataptic/docs/mkdocs/js/search' {
  declare module.exports: any;
}

declare module 'neataptic/docs/mkdocs/js/text' {
  declare module.exports: any;
}

declare module 'neataptic/graph/graph' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.10/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.10/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.11/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.11/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.12/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.12/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.13/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.13/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.14/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.14/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.15/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.15/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.16/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.16/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.17/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.17/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.18/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.18/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.19/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.19/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.20/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.20/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.21/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.21/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.22/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.22/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.23/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.23/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.24/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.24/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.25/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.25/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.26/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.26/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.27/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.27/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.28/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.28/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.29/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.29/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.30/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.30/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.31/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.31/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.32/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.32/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.33/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.33/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.34/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.2.34/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.0/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.0/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.1/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.1/neataptic.min' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.2/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.3/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.4/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.5/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.6/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.7/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.8/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.3.9/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.4.0/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.4.1/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.4.2/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.4.3/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.4.4/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/cdn/1.4.5/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/field' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/food' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/import' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/main' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/player' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/population' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/events' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/import' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/neural' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/randomColor' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/events' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/graph' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/import' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/neural' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/webcola' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/playground/events' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/playground/graph' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/playground/import' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/playground/neural' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/field' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/graph' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/import' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/main' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/player' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/population' {
  declare module.exports: any;
}

declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/walker' {
  declare module.exports: any;
}

declare module 'neataptic/src/architecture/architect' {
  declare module.exports: any;
}

declare module 'neataptic/src/architecture/connection' {
  declare module.exports: any;
}

declare module 'neataptic/src/architecture/group' {
  declare module.exports: any;
}

declare module 'neataptic/src/architecture/layer' {
  declare module.exports: any;
}

declare module 'neataptic/src/architecture/network' {
  declare module.exports: any;
}

declare module 'neataptic/src/architecture/node' {
  declare module.exports: any;
}

declare module 'neataptic/src/config' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/activation' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/connection' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/cost' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/crossover' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/gating' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/methods' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/mutation' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/rate' {
  declare module.exports: any;
}

declare module 'neataptic/src/methods/selection' {
  declare module.exports: any;
}

declare module 'neataptic/src/multithreading/multi' {
  declare module.exports: any;
}

declare module 'neataptic/src/multithreading/workers/browser/testworker' {
  declare module.exports: any;
}

declare module 'neataptic/src/multithreading/workers/node/testworker' {
  declare module.exports: any;
}

declare module 'neataptic/src/multithreading/workers/node/worker' {
  declare module.exports: any;
}

declare module 'neataptic/src/multithreading/workers/workers' {
  declare module.exports: any;
}

declare module 'neataptic/src/neat' {
  declare module.exports: any;
}

declare module 'neataptic/src/neataptic' {
  declare module.exports: any;
}

declare module 'neataptic/test/dist' {
  declare module.exports: any;
}

declare module 'neataptic/test/neat' {
  declare module.exports: any;
}

declare module 'neataptic/test/network' {
  declare module.exports: any;
}

declare module 'neataptic/test/src' {
  declare module.exports: any;
}

declare module 'neataptic/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'neataptic/dist/neataptic.js' {
  declare module.exports: $Exports<'neataptic/dist/neataptic'>;
}
declare module 'neataptic/dist/worker.js' {
  declare module.exports: $Exports<'neataptic/dist/worker'>;
}
declare module 'neataptic/docs/cdn/1.2.10/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.10/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.10/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.10/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.11/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.11/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.11/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.11/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.12/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.12/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.12/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.12/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.13/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.13/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.13/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.13/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.14/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.14/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.14/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.14/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.15/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.15/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.15/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.15/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.16/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.16/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.16/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.16/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.17/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.17/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.17/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.17/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.18/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.18/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.18/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.18/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.19/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.19/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.19/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.19/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.20/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.20/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.20/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.20/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.21/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.21/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.21/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.21/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.22/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.22/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.22/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.22/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.23/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.23/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.23/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.23/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.24/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.24/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.24/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.24/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.25/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.25/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.25/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.25/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.26/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.26/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.26/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.26/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.27/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.27/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.27/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.27/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.28/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.28/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.28/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.28/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.29/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.29/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.29/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.29/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.30/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.30/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.30/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.30/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.31/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.31/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.31/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.31/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.32/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.32/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.32/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.32/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.33/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.33/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.33/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.33/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.2.34/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.34/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.2.34/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.2.34/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.3.0/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.0/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.0/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.0/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.3.1/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.1/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.1/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.1/neataptic.min'>;
}
declare module 'neataptic/docs/cdn/1.3.2/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.2/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.3/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.3/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.4/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.4/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.5/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.5/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.6/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.6/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.7/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.7/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.8/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.8/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.3.9/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.3.9/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.4.0/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.4.0/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.4.1/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.4.1/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.4.2/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.4.2/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.4.3/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.4.3/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.4.4/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.4.4/neataptic'>;
}
declare module 'neataptic/docs/cdn/1.4.5/neataptic.js' {
  declare module.exports: $Exports<'neataptic/docs/cdn/1.4.5/neataptic'>;
}
declare module 'neataptic/docs/js/articles/agar.ioai/field.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/agar.ioai/field'>;
}
declare module 'neataptic/docs/js/articles/agar.ioai/food.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/agar.ioai/food'>;
}
declare module 'neataptic/docs/js/articles/agar.ioai/import.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/agar.ioai/import'>;
}
declare module 'neataptic/docs/js/articles/agar.ioai/main.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/agar.ioai/main'>;
}
declare module 'neataptic/docs/js/articles/agar.ioai/player.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/agar.ioai/player'>;
}
declare module 'neataptic/docs/js/articles/agar.ioai/population.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/agar.ioai/population'>;
}
declare module 'neataptic/docs/js/articles/classifycolors/events.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/classifycolors/events'>;
}
declare module 'neataptic/docs/js/articles/classifycolors/import.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/classifycolors/import'>;
}
declare module 'neataptic/docs/js/articles/classifycolors/neural.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/classifycolors/neural'>;
}
declare module 'neataptic/docs/js/articles/classifycolors/randomColor.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/classifycolors/randomColor'>;
}
declare module 'neataptic/docs/js/articles/neuroevolution/events.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/neuroevolution/events'>;
}
declare module 'neataptic/docs/js/articles/neuroevolution/graph.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/neuroevolution/graph'>;
}
declare module 'neataptic/docs/js/articles/neuroevolution/import.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/neuroevolution/import'>;
}
declare module 'neataptic/docs/js/articles/neuroevolution/neural.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/neuroevolution/neural'>;
}
declare module 'neataptic/docs/js/articles/neuroevolution/webcola.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/neuroevolution/webcola'>;
}
declare module 'neataptic/docs/js/articles/playground/events.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/playground/events'>;
}
declare module 'neataptic/docs/js/articles/playground/graph.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/playground/graph'>;
}
declare module 'neataptic/docs/js/articles/playground/import.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/playground/import'>;
}
declare module 'neataptic/docs/js/articles/playground/neural.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/playground/neural'>;
}
declare module 'neataptic/docs/js/articles/target-seekingai/field.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/target-seekingai/field'>;
}
declare module 'neataptic/docs/js/articles/target-seekingai/graph.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/target-seekingai/graph'>;
}
declare module 'neataptic/docs/js/articles/target-seekingai/import.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/target-seekingai/import'>;
}
declare module 'neataptic/docs/js/articles/target-seekingai/main.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/target-seekingai/main'>;
}
declare module 'neataptic/docs/js/articles/target-seekingai/player.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/target-seekingai/player'>;
}
declare module 'neataptic/docs/js/articles/target-seekingai/population.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/target-seekingai/population'>;
}
declare module 'neataptic/docs/js/articles/target-seekingai/walker.js' {
  declare module.exports: $Exports<'neataptic/docs/js/articles/target-seekingai/walker'>;
}
declare module 'neataptic/docs/js/base.js' {
  declare module.exports: $Exports<'neataptic/docs/js/base'>;
}
declare module 'neataptic/docs/js/bootstrap-3.0.3.min.js' {
  declare module.exports: $Exports<'neataptic/docs/js/bootstrap-3.0.3.min'>;
}
declare module 'neataptic/docs/js/highlight.pack.js' {
  declare module.exports: $Exports<'neataptic/docs/js/highlight.pack'>;
}
declare module 'neataptic/docs/js/jquery-1.10.2.min.js' {
  declare module.exports: $Exports<'neataptic/docs/js/jquery-1.10.2.min'>;
}
declare module 'neataptic/docs/mkdocs/js/lunr.min.js' {
  declare module.exports: $Exports<'neataptic/docs/mkdocs/js/lunr.min'>;
}
declare module 'neataptic/docs/mkdocs/js/mustache.min.js' {
  declare module.exports: $Exports<'neataptic/docs/mkdocs/js/mustache.min'>;
}
declare module 'neataptic/docs/mkdocs/js/require.js' {
  declare module.exports: $Exports<'neataptic/docs/mkdocs/js/require'>;
}
declare module 'neataptic/docs/mkdocs/js/search.js' {
  declare module.exports: $Exports<'neataptic/docs/mkdocs/js/search'>;
}
declare module 'neataptic/docs/mkdocs/js/text.js' {
  declare module.exports: $Exports<'neataptic/docs/mkdocs/js/text'>;
}
declare module 'neataptic/graph/graph.js' {
  declare module.exports: $Exports<'neataptic/graph/graph'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.10/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.10/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.10/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.10/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.11/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.11/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.11/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.11/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.12/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.12/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.12/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.12/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.13/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.13/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.13/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.13/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.14/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.14/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.14/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.14/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.15/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.15/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.15/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.15/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.16/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.16/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.16/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.16/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.17/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.17/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.17/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.17/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.18/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.18/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.18/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.18/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.19/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.19/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.19/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.19/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.20/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.20/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.20/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.20/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.21/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.21/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.21/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.21/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.22/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.22/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.22/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.22/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.23/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.23/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.23/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.23/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.24/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.24/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.24/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.24/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.25/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.25/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.25/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.25/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.26/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.26/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.26/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.26/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.27/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.27/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.27/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.27/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.28/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.28/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.28/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.28/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.29/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.29/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.29/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.29/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.30/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.30/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.30/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.30/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.31/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.31/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.31/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.31/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.32/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.32/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.32/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.32/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.33/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.33/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.33/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.33/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.34/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.34/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.2.34/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.2.34/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.0/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.0/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.0/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.0/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.1/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.1/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.1/neataptic.min.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.1/neataptic.min'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.2/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.2/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.3/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.3/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.4/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.4/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.5/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.5/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.6/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.6/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.7/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.7/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.8/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.8/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.3.9/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.3.9/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.4.0/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.4.0/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.4.1/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.4.1/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.4.2/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.4.2/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.4.3/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.4.3/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.4.4/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.4.4/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/cdn/1.4.5/neataptic.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/cdn/1.4.5/neataptic'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/field.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/agar.ioai/field'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/food.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/agar.ioai/food'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/import.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/agar.ioai/import'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/main.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/agar.ioai/main'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/player.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/agar.ioai/player'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/agar.ioai/population.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/agar.ioai/population'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/events.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/classifycolors/events'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/import.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/classifycolors/import'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/neural.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/classifycolors/neural'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/classifycolors/randomColor.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/classifycolors/randomColor'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/events.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/neuroevolution/events'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/graph.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/neuroevolution/graph'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/import.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/neuroevolution/import'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/neural.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/neuroevolution/neural'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/neuroevolution/webcola.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/neuroevolution/webcola'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/playground/events.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/playground/events'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/playground/graph.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/playground/graph'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/playground/import.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/playground/import'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/playground/neural.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/playground/neural'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/field.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/target-seekingai/field'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/graph.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/target-seekingai/graph'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/import.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/target-seekingai/import'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/main.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/target-seekingai/main'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/player.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/target-seekingai/player'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/population.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/target-seekingai/population'>;
}
declare module 'neataptic/mkdocs/theme/js/articles/target-seekingai/walker.js' {
  declare module.exports: $Exports<'neataptic/mkdocs/theme/js/articles/target-seekingai/walker'>;
}
declare module 'neataptic/src/architecture/architect.js' {
  declare module.exports: $Exports<'neataptic/src/architecture/architect'>;
}
declare module 'neataptic/src/architecture/connection.js' {
  declare module.exports: $Exports<'neataptic/src/architecture/connection'>;
}
declare module 'neataptic/src/architecture/group.js' {
  declare module.exports: $Exports<'neataptic/src/architecture/group'>;
}
declare module 'neataptic/src/architecture/layer.js' {
  declare module.exports: $Exports<'neataptic/src/architecture/layer'>;
}
declare module 'neataptic/src/architecture/network.js' {
  declare module.exports: $Exports<'neataptic/src/architecture/network'>;
}
declare module 'neataptic/src/architecture/node.js' {
  declare module.exports: $Exports<'neataptic/src/architecture/node'>;
}
declare module 'neataptic/src/config.js' {
  declare module.exports: $Exports<'neataptic/src/config'>;
}
declare module 'neataptic/src/methods/activation.js' {
  declare module.exports: $Exports<'neataptic/src/methods/activation'>;
}
declare module 'neataptic/src/methods/connection.js' {
  declare module.exports: $Exports<'neataptic/src/methods/connection'>;
}
declare module 'neataptic/src/methods/cost.js' {
  declare module.exports: $Exports<'neataptic/src/methods/cost'>;
}
declare module 'neataptic/src/methods/crossover.js' {
  declare module.exports: $Exports<'neataptic/src/methods/crossover'>;
}
declare module 'neataptic/src/methods/gating.js' {
  declare module.exports: $Exports<'neataptic/src/methods/gating'>;
}
declare module 'neataptic/src/methods/methods.js' {
  declare module.exports: $Exports<'neataptic/src/methods/methods'>;
}
declare module 'neataptic/src/methods/mutation.js' {
  declare module.exports: $Exports<'neataptic/src/methods/mutation'>;
}
declare module 'neataptic/src/methods/rate.js' {
  declare module.exports: $Exports<'neataptic/src/methods/rate'>;
}
declare module 'neataptic/src/methods/selection.js' {
  declare module.exports: $Exports<'neataptic/src/methods/selection'>;
}
declare module 'neataptic/src/multithreading/multi.js' {
  declare module.exports: $Exports<'neataptic/src/multithreading/multi'>;
}
declare module 'neataptic/src/multithreading/workers/browser/testworker.js' {
  declare module.exports: $Exports<'neataptic/src/multithreading/workers/browser/testworker'>;
}
declare module 'neataptic/src/multithreading/workers/node/testworker.js' {
  declare module.exports: $Exports<'neataptic/src/multithreading/workers/node/testworker'>;
}
declare module 'neataptic/src/multithreading/workers/node/worker.js' {
  declare module.exports: $Exports<'neataptic/src/multithreading/workers/node/worker'>;
}
declare module 'neataptic/src/multithreading/workers/workers.js' {
  declare module.exports: $Exports<'neataptic/src/multithreading/workers/workers'>;
}
declare module 'neataptic/src/neat.js' {
  declare module.exports: $Exports<'neataptic/src/neat'>;
}
declare module 'neataptic/src/neataptic.js' {
  declare module.exports: $Exports<'neataptic/src/neataptic'>;
}
declare module 'neataptic/test/dist.js' {
  declare module.exports: $Exports<'neataptic/test/dist'>;
}
declare module 'neataptic/test/neat.js' {
  declare module.exports: $Exports<'neataptic/test/neat'>;
}
declare module 'neataptic/test/network.js' {
  declare module.exports: $Exports<'neataptic/test/network'>;
}
declare module 'neataptic/test/src.js' {
  declare module.exports: $Exports<'neataptic/test/src'>;
}
declare module 'neataptic/webpack.config.js' {
  declare module.exports: $Exports<'neataptic/webpack.config'>;
}
